# fly.toml file generated for lively-sunset-9810 on 2022-09-05T13:46:34-04:00

app = "lively-sunset-9810"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  PHX_HOST = "lively-sunset-9810.fly.dev"
  DATABASE_PATH = "/data/data_volume/database.db"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "data_volume"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
